apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: java-webapp-pipeline
  namespace: java-pipeline
spec:
  params:
    - name: git-url
    - name: git-revision
    - name: build-name
    - name: namespace
  workspaces:
    - name: shared-workspace
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: deleteExisting
          value: "true"
        - name: subdirectory
          value: "deployment-ocs"
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: maven-build
      taskRef:
        name: maven-build
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: war-sanity-check
      taskRef:
        name: war-sanity-check
      runAfter:
        - maven-build
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: trigger-build
      taskRef:
        name: shipwright-trigger
      runAfter:
        - war-sanity-check
      params:
        - name: BUILD_NAME
          value: $(params.build-name)
        - name: NAMESPACE
          value: $(params.namespace)

    - name: deploy
      taskRef:
        name: deploy
      runAfter:
        - trigger-build
      workspaces:
        - name: source
          workspace: shared-workspaceapiVersion: tekton.dev/v1
