apiVersion: v1
kind: PersistentVolume
metadata:
  name: java-pipeline-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  # Manual PV, no StorageClass
  hostPath:
    path: "/mnt/java-pipeline-data"
