apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: java-pipeline-pvc
  namespace: java-pipeline
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""  # Match manual PV
  volumeName: java-pipeline-pv  # Bind to our PV
