apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: java-pipeline-pvc
  namespace: java-pipeline
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: crc-csi-hostpath-provisioner
