apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: tektoncd-operator
  namespace: openshift-pipelines
spec:
  channel: stable
  name: tektoncd-operator
  source: tekton-catalog
  sourceNamespace: openshift-marketplace
