# java-webapp/k8s/rbac/argocd-cluster-role-cbs.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-app-controller-cbs
rules:
- apiGroups: ["shipwright.io"]
  resources: ["clusterbuildstrategies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
