# rbac/argocd-cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-app-controller-cluster
rules:
  - apiGroups: ["shipwright.io"]
    resources: ["clusterbuildstrategies"]
    verbs: ["get", "list", "watch", "patch", "update", "create"]
