# java-webapp/k8s/rbac/argocd-cluster-rolebinding-cbs.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-app-controller-cbs-binding
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
roleRef:
  kind: ClusterRole
  name: argocd-app-controller-cbs
  apiGroup: rbac.authorization.k8s.io
