apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-app
  namespace: openshift-gitops
spec:
  source:
    repoURL: https://github.com/kevin-biot/deployment-ocs.git
    targetRevision: main
    path: awx
  destination:
    server: https://kubernetes.default.svc
    namespace: awx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
