apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-webapp
  namespace: openshift-gitops  # This is where ArgoCD is installed
spec:
  project: default

  source:
    repoURL: https://github.com/kevin-biot/deployment-ocs.git
    targetRevision: main
    path: java-webapp/k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: java-pipeline

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
