apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operators
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/kevin-biot/deployment-ocs.git
    path: operators
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
