apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-app
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/kevin-biot/deployment-ocs.git
    targetRevision: main
    path: tekton
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-pipelines
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
