apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: awx-operator
  namespace: awx
spec:
  channel: alpha
  name: awx-operator
  source: awx-catalog
  sourceNamespace: openshift-marketplace
