apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: openshift-gitops
data:
  policy.csv: |
    p, role:admin, applications, *, */*, allow
    g, system:cluster-admins, role:admin
    g, cluster-admins, role:admin
    g, system:authenticated, role:admin
  policy.default: role:admin
  scopes: '[sub, groups]'
